### PR TITLE
Update packages and code to support strapi-v5 and strapi/design-system-v2

### PR DESCRIPTION
**Pull request by alexleach**
Hi,

Please excuse my coming in out of nowhere like this!

I've been working on updating various strapi modules (as required by [medusa-strapi-repo](https://github.com/SGFGOV/medusa-strapi-repo)) to work with [strapi version 5 (beta)](https://github.com/strapi/strapi/tree/v5.0.0-beta.5), and [strapi/design-system v2 (beta)](https://github.com/strapi/design-system/tree/releases/2.0.0). This package is one that needed some manual updates. 🙂 

While updating the Strapi modules, I also ran `npm-check-updates -u` to update other dependences too, as well as the `engine` to node version 20.

There are quite a few [breaking changes in strapi/design-system v2](https://github.com/strapi/design-system/blob/%40strapi/design-system%402.0.0-beta.2/BREAKING_CHANGES.md) that affected this package:

  - `<Refresh />` has been renamed to `<ArrowClockwise />`
  - `<Select />` and `<Option />` have been removed and in this package, replaced with `<SingleSelect />` and `<SingleSelectOption />`, respectively. (There are also `<MultiSelect />` and `<MultiOption />` variants too now.)
  - Introduction of Type definitions. This appeared to break a lot of `onChange` and `onValueChange` implementations in this package, which needed to be changed to arrow functions. Most file changes in this PR are to allow this.

Some additional code changes required by other package updates:

  - I found I needed to explicitly add `react-router-dom` as a dependency. This then became version 6, which also had introduced some [breaking changes]https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v6), that had to be changed in `HomePage/index.tsx`

  - The latest `axios` version also required some minor changes in how the headers are updated.

Another bug fix will be required in the upstream `strapi/design-system` package, which I will create a PR for as well, to get this compiling successfully.

Anyway, I hope this PR will be useful in keeping this package and its dependencies up-to-date 🙂 

Kind regards,
Alex

PS. I would have liked to create a PR for this to a new branch, but I don't think GitHub allows that...

### CODE REVIEW

**Comment by alexleach** [comment]
Oh yeah, also I deleted `package-lock.json`. I use `yarn`, which complains about its existence, so I prefer not have a lock file at all if I'm honest...

**Comment by MaksZhukov** [comment]
@alexleach Hey man!
First of all, thank you for your contribution 😎
Some questions I have:
1) Will the changes work on strapi v4? If no, I need to support like 2 versions v1 for strapi v4 and v2(now beta) for strapi v5?
2) Do you know when you install a package npm uses install it's packages from package-lock, not from package.json(that have not strickt versions)?

**Comment by alexleach** [comment]
Hi @MaksZhukov,

You're welcome, hope it might be of use!

Great question! I understand not wanting to maintain multiple versions of a package! To be honest, I've not tested with strapi v4... 😬  I think most of the updates made to `package.json` should work with Strapi v4. For example, bumping the node version to 20 shouldn't be an issue, nor should the code changes related to `react-router-dom` and `axios` libraries, if their versions are bumped.

There are however lots of breaking changes related to strapi/design-system v2 (beta). Just yesterday, [PR #1693](https://github.com/strapi/design-system/pull/1693) was merged that introduced a whole slew of new errors, related to the use of the `label` attribute. That certainly caught me off guard!

Thinking about it now, and based on your question, it probably does make sense to split this PR, so that the package updates can be merged into your main branch, and the breaking changes related to `strapi-design-system` can be put into a separate branch, if that's something you're willing to do?

---

If I understand your second question, yes I know `package-lock.json` does strictly adhere to certain package versions. Personally, I find package version management with npm a real pain! `npm update` and `npm upgrade` rarely actually do any updates or upgrades to packages, and `npm-check-updates` needs to be used instead. With this repo in particular, as it's a strapi plugin, I'd prefer the parent strapi package to manage most package versions. For instance, `package-lock.json` requires `@strapi/admin:4.6.1`, but shouldn't `@strapi/strapi` manage that?

---

Sorry if I tried to do too much with this PR! As mentioned, I'm trying to get a Strapi / Medusa application running with Strapi v5, even if it is still in beta. But yeah, perhaps that's too much administrative burden, so apologies if I've tried doing too much here! 🙃 

All the best,
Alex

**Comment by MaksZhukov** [comment]
@alexleach You can leave the changes that won't break v4 version for now

**Comment by dvy1hc** [comment]
Hi @MaksZhukov, do you have a plan to release the new version support strapi v5?

**Comment by MaksZhukov** [comment]
@dvy1hc Hey! Sure. The pr is not working properly
I tried to migrate to v5, but faced with some problems in v5 with my plugin.
So I'm waiting for some new versions in v5 maybe it will help

**Pull request closed without merging**
